### ISSUE TITLE
Multiple Resultset Support

### ISSUE THREAD

**Issue by italanchan** [invokermain/pymssql-utils#22]
Is it possible to support Multiple Resultset?

**Comment by mralanchan** [comment]
```
import pymssqlutils as sql

dbconn = dict(server='dbserver', user='...', password='...', database='testdb', appname = '....')

#query = 'select * from table1 where col1 = 123; select * from table2 where col1 = 567'
query = 'Select getdate() now;select 1 + 1 value1, 2 + 2 value2'
result = sql.query(query, None, **dbconn)
r = result.to_json() # get json result
d = result.to_dataframe() # get two dataframes
print(r)
print(d[0])
print(d[1])
```

The above code cannot returns two resultsets.

**Comment by italanchan** [comment]
The original case is call stored procedure which return two recordsets.  

query = 'exec mysp'
result = sql.query(query , **dbconn)

**Comment by invokermain** [comment]
Hey I just released 0.3. Which adds support for multiple result sets. It required some 'low level' changes to how the library interacts with the cursor, but a solid improvement all round so thank you for raising the issue. Could you test it out and let me know if it works for you?

You can now move between the result sets returned by a query using the `next_set()` and `previous_set()` methods on the `DatabaseResult` instance. When you move to another set, the `data`, `raw_data`, `columns` etc attributes will reflect the new set's data.

**Comment by mralanchan** [comment]
Tested my code, it work.  ^^
```
import pymssqlutils as sql

dbconn = dict(server='dbserver', user='...', password='...', database='testdb', appname = '....')

query = 'exec get_invoice_with_detail(123456)'
result = sql.query(query, None, **dbconn)

# get dataframes
dfresult = []
for i in range(result.set_count):
    data = result.to_dataframe()
    dfresult.append(data)
    result.next_set()

print(dfresult[0])
print(dfresult[1])
```

**Comment by invokermain** [comment]
nice one
